### ISSUE TITLE
E2 functions

### ISSUE THREAD

**Issue by noth1ng1996** [nrlulz/ACF#142]
Some of ACF e2 functions won't return correct result. For example function Engine:acfFuelUse(), where 'Engine' is entity variable connected to acf engine's 'Entity' output, which is connected to not empty active fuel tanks. As a result while, ACF engine's 'Fuel use' output gives you correct value, function Engine:acfFuelUse() returns 0.

**Comment by Fervidusletum** [comment]
Thanks for the heads up, I'll look into it.

**Comment by Fervidusletum** [comment]
Fixed in 90571bcffa4b99af7c07f69bc7df35e9da3cf1d1.
