### ISSUE TITLE
ACF Ammo Lua errors

### ISSUE THREAD

**Issue by thegrb93** [nrlulz/ACF#144]
```
[ERROR] addons/acf/lua/entities/acf_ammo.lua:370: attempt to index field 'BulletData' (a nil value)
  1. AmmoMass - addons/acf/lua/entities/acf_ammo.lua:370
   2. unknown - addons/acf/lua/entities/acf_ammo.lua:417
```

**Comment by Fervidusletum** [comment]
Looks like either the ammo was uninitialized or something overwrote some tables on it.  Let me know if you can reproduce it, otherwise I suspect the cause is external to ACF.

**Comment by thegrb93** [comment]
Maybe it happens upon duplicating? I'm not sure, I found there were a ton of these errors in my error log.

**Comment by Fervidusletum** [comment]
Most likely not dupe2 by itself.  There's unfortunately not enough information where the error happens, it's just saying that an ammo crate isn't able to calculate its weight because there's no data on the bullets it should contain.  There's nothing indicating why it didn't have that data.
