### ISSUE TITLE
Need easier way to edit acf_gearbox.lua entity

### ISSUE THREAD

**Issue by monkstick** [nrlulz/ACF#146]
I currently have an automatic gearbox I wrote and maintain on my server. It works great, but it requires me editing acf_gearbox.lua.  Is there any way I can make my automatic gearbox a separate file that wouldn't require me to re-edit after every update?

**Comment by Fervidusletum** [comment]
Not easily, no.  The only things I can think of would necessitate changing other files, leading to same problem.

**Comment by Bubbus** [comment]
https://github.com/nrlulz/ACF/blob/master/lua/acf/shared/acf_userconfig_example.lua shows a way to set up some configuration outside the reach of version-control overwrites.  I use this file to load custom weapons into ACF for my server - maybe a similar approach could work for gearboxes if their code was made to support it.

**Comment by monkstick** [comment]
Nah I don't think that will work (Although I will try a workaround, maybe backup the gearbox.lua functions, insert my own code then resume them?) as I also use this for custom engines.  I need specific control over the server-side part of the entity for such things as "	Gearbox.Auto = List.Mobility[Id].automatic or false", "		table.insert(Inputs,"Min-Rpm")
		table.insert(Inputs,"Max-Rpm")" and the Think part.

Is there any way I could copy paste the current gearbox entity, so my gearboxes are "technically" not ent.gearboxe, but ent.Gearbox2 for example.  That way I could have all my own code for it, but it still appears in the acf Mobility window and is still functional.

**Comment by Fervidusletum** [comment]
You'd either have to make your own tool to spawn them, or modify the acf tool lua to support it (which leads to the same problem you have now)

**Comment by monkstick** [comment]
Could I possibly try to commit my code so the automatic gearboxes are stock acf haha.

**Comment by Fervidusletum** [comment]
Yep! :) I've been meaning to add an auto-gearbox for some time, just haven't gotten around to it, and I'd be happy to add yours.

There's a couple ways to go about it.  You can fork this project (there's a button on the main project page, top right, or click the pull request button) and submit a pull request with your changes.  Alternatively I'd take a dropbox (or your distribution of choice) link with a zip containing the lua and commit it from my end.

**Comment by Amplar** [comment]
How does the gearbox work, and is it balanced with other gearboxes? I've wanted an automatic gearbox for eons, but it shouldn't outperform a manual trans.
Auto gearbox:
-Fewer gears (selection of 3-5-7 boxes)
-Higher torque rating than manuals
-Very heavy
-Slow to respond to shifting.
-Shifting should be done by an input of rpm, throttle and speed
-Torque converter instead of a clutch
