### ISSUE TITLE
Indestructable armor :(

### ISSUE THREAD

**Issue by koskok2695** [nrlulz/ACF#147]
Hey guys,

Im new to acf and the first thing i played with was armor.I gave some properties to a metal plate, set up a massive cannon and started firing at the plate.....and nothing happened!I checked the gun's properties, tried various types of ammunition (each time maxing out their properties to make em powerful) but still that prop wouldnt receive damage!I even saw the shells impact on it, explode on it, penetrate it and generally interact perfectly fine BUT NO DAMAGE WAS DONE!Is there something Im missing? Something I did wrong?Any settings I need to adjust?Please help me cuz I really like this addon and want to play with as its meant to be played.

**Comment by Fervidusletum** [comment]
It really depends on your armor prop and properties, and shell setup. Usually maxing out sliders is a bad idea, leading to subpar performance, and certain round types don't deal much damage to armor.  Huge props have huge amounts of health, so they take very little damage especially with armor.
