### ISSUE TITLE
Error: The XML response contains invalid XML

### ISSUE THREAD

**Issue by Inchs** [nrlulz/ACF#148]
Honestly, can't tell you much about this but when I'm installing using SVN, somewhere near the end at sounds this happens.
Error: The XML response contains invalid XML
No more info or anything, honestly I'm sorry for posting this here, but there is nowhere else.

**Comment by Fervidusletum** [comment]
Only suggestions I can come up with are to try a checkout in a new folder with a different name, or try using TortoiseGIT instead of TortoiseSVN.  

For SVN, use https://github.com/nrlulz/ACF/trunk
