### ISSUE TITLE
HE is too powerful

### ISSUE THREAD

**Issue by Amplar** [nrlulz/ACF#149]
After some testing, it is indeed too damaging to high health, low armor props. HE works well against brittle armor, like it should, but baseplates (15-50mm) are getting raped by by mid-tier HE. I think biasing HE damage absorbtion towards health instead of armor would help correct this instead of nerfing HE and making -duct props not vulnerable anymore.

**Comment by Fervidusletum** [comment]
Hopefully addressed in 982ca43dbac948ad8f143c17f53276270a9d1428.
