### ISSUE TITLE
ACF do not load

### ISSUE THREAD

**Issue by fakepiratinha** [nrlulz/ACF#150]
Hello guys, i dont know how to tell you this but my acf do not work.
i downloaded the zip and extract the zip in the addons folder, then i start my gmod and is like gmod was ignoring the acf.
No acf tool, no props.
how is this even possible?????????????

Running Ubuntu 14.10

**Comment by WHO-ARE-WE** [comment]
I also have this problem and I'm running Ubuntu 14.10.

**Comment by fakepiratinha** [comment]
I HAVE THE FU**ING SOLUTION!!!!
just extract the ACF folders (lua, materials, models etc) in the gmod folder, like that:
normal: GarrysMod/garrysmod/addons/acf/(folders)
solution: GarrysMod/garrysmod/(folders)

WARNING: DO A BACKUP OF YOUR GMOD BEFORE DO IT!!!
