### ISSUE TITLE
ACF models and sounds do not show up on Linux

### ISSUE THREAD

**Issue by WHO-ARE-WE** [nrlulz/ACF#151]
Hello,

I have installed ACF normally (git clone into addons/ folder), yet the models and sounds do not show up in game. Instead I see errors and console messages regarding missing elements with directory paths indicating ACF models and sounds. My friends, running on Windows, have installed ACF the same way and everything works fine.

I heard one possible cause might be that ACF expects the underlying filesystem to be case-insensitive, which is not the case with EXT filesystems. I'm not that familiar with Lua so I can't dig into the source code that well.

Any ideas?

Thanks!

**Comment by fakepiratinha** [comment]
i really dont have any ideia why this is happen. i have the same problem as you and i have other svn donwloaded addons like acf running with no problems

**Comment by fakepiratinha** [comment]
hello mate, i discovered a way to fix this:
1- do a backup of your gmod
2- pick the acf folders (normal: Garrysmod/garrysmod/acf/-folders-) and put in the garrysmod folder (Garrysmod/garrysmod/-folders-)
3- if you want you can delete the acf folder in addons
