### ISSUE TITLE
ACF Turbo Chargers and Super Chargers

### ISSUE THREAD

**Issue by saucysloth** [nrlulz/ACF#154]
<h1>Turbo Chargers and Super Chargers</h1>
I think they should be implemented as it can benefit people. My basic idea is that the engine can handle a certian amount of 'stress' or PSI, the player can set the boost over that, but the engine will not last too long, and could explode. There should be a Small Turbo to Large, and the same goes for Superchargers. The turbo could 'latch' onto the engine ontop or side, through ports.

Thanks.

<h5>(PS, please give feedback!)</h5>

**Comment by Fervidusletum** [comment]
See issue #117, Amplars reply pretty much sums it up.
