### ISSUE TITLE
Ability to disable  parts of acf

### ISSUE THREAD

**Issue by Bryantdl7** [nrlulz/ACF#156]
I tried looking around, but here is what I hope to have as a feature; 
I want the power to disable the weapon and armor part of acf, as my server is more of a build server than a 203 mm howitzer-blasting server. 
Is there a way to disable parts of the addon? If not, will this be eventually an addition?

**Comment by thegrb93** [comment]
Go to ACF\lua\acf\shared and delete whatever you don't want.

**Comment by Fervidusletum** [comment]
I believe there are concmds, settings in the acf_globals.lua, and damage disabling modes you can use.

**Comment by Bubbus** [comment]
acf_gunfire 0
