### ISSUE TITLE
Prevent drive shaft from breaking

### ISSUE THREAD

**Issue by codylewiz** [nrlulz/ACF#158]
is there a way to prevent the drive shaft from breaking aka remove the funtion, I have a free build race server though everyone who sets up suspention the Drive shaft breaks on every bump

**Comment by Fervidusletum** [comment]
The only way is to have more room between components, so small position jitters result in smaller angle deviation, making it much harder to push the link beyond the 45 degree limit.

**Comment by codylewiz** [comment]
I found that out A few hours I posted forgot to update though
