### ISSUE TITLE
Negative gears arent working

### ISSUE THREAD

**Issue by codylewiz** [nrlulz/ACF#159]
When I try to make a reverse gear it doesnt put it in drive it just goes forward unless I update transmission, then reverse only works once

**Comment by Fervidusletum** [comment]
Make sure your control chip/wiring is working as intended; reverse gears are working normally.

**Comment by codylewiz** [comment]
@name ACF
@inputs W S
@outputs Throttle Gear
@persist
@trigger
 
 
if(first())
{ Gear = 1
}
 
 
if(W == 1)
{ if(Gear == 8) { Gear = 1 Throttle = 100 } else { Throttle = 100 }
}
else
{ Throttle = 0
}
 
if(S == 1)
{ Gear = 8 Throttle = 100
}
 
if(dupefinished())
{ reset()
}
Thats My E2 chip worked just fine and then just stopped working all of a sudden.

**Comment by Fervidusletum** [comment]
try
````
@name ACF
@inputs W S
@outputs Throttle Gear
@persist
@trigger all

if (duped()|dupefinished()) { reset() }
if (first()) { Gear = 1 }

Throttle = 100*(W|S)
Gear = S ? 8 : 1
````

The `S ? 8 : 1` is a shortened form of `if then else`, and translates to `if S then 8 else 1`.  I would recommend heading over to wiremod or facepunch forums if you need help writing e2, as this isn't really the place for it.

**Comment by codylewiz** [comment]
Not working What I mean is If I swich the gear to the negative gear "8" it wont go in reverse

**Comment by Fervidusletum** [comment]
Try on different servers, with different gearboxes and different gear setups.  This is most likely either an issue with your gearbox/control chip setup, or an issue with your client/server being on an extremely old branch of ACF.

**Comment by codylewiz** [comment]
is red engines New or Grey Engines new?

**Comment by Fervidusletum** [comment]
Grey engines that are recolorable are newer.
