### ISSUE TITLE
[Suggestion] New Engine (Larger Engine?)

### ISSUE THREAD

**Issue by brucektrain** [nrlulz/ACF#160]
Will You Guys can Add V16?  Here the video of the engine starting up, https://youtu.be/oJzbegysv9c?t=1m48s   Ty,  (It's Good thing If was added, People who build trains etc, they can might use those engine , that can have incudes 2 gearbox Linking, for both of bogeys,)

**Comment by Fervidusletum** [comment]
No plans to add v16 ATM. There is an extra acf engine pack on workshop by gamerpaddy  that may have them.
