### ISSUE TITLE
Shooting certain classes with ACF causes massive lag

### ISSUE THREAD

**Issue by monkstick** [nrlulz/ACF#163]
I discovered this with Bubbus's handhelds, but the same rules apply.  If you shoot the class of Debris,  func_door,  prop_ragdoll and many others,  you get an infinite loop in sv_acfballistics.lua

		if Retry == "Penetrated" then		--If we should do the same trace again, then do so
			if Bullet.OnPenetrated then Bullet.OnPenetrated(Index, Bullet, FlightRes) end
			ACF_BulletClient( Index, Bullet, "Update" , 2 , FlightRes.HitPos  )
			ACF_DoBulletsFlight( Index, Bullet )  <-- This then goes back to the top and repeats

Problem is, is the debris, func_door etc don't take damage or let projectiles though them, so we get a loop.

I have made myself a temp fix under line 141

		local Retry = ACF_BulletPropImpact( Index, Bullet, FlightRes.Entity , FlightRes.HitNormal , FlightRes.HitPos , FlightRes.HitGroup )				--If we hit stuff then send the resolution to the damage function	
		if((tostring(FlightRes.Entity:GetClass()) == "func_door" or (tostring(FlightRes.Entity:GetClass()) == "debris") or tostring(FlightRes.Entity:GetClass()) == "prop_ragdoll")) then FlightRes.Entity:Remove() return end 

This completely fixes the issue for me, but its not exactly an elegant solution.

**Comment by Fervidusletum** [comment]
I have a few ideas what the culprit could be, but I'm having trouble replicating the problem.  Do you have any errors in the log that can indicate where the problem is happening?

**Comment by monkstick** [comment]
To replicate the problem,  simply shoot the debris class with an acf weapon.  You can also dupe some debris and paste it and it keeps its class,  which makes debugging easier.

**Comment by Fervidusletum** [comment]
I will try that, though I wasn't getting any lag firing at doors or ragdolls on SP, listen, or dedi server I have access to.

**Comment by Fervidusletum** [comment]
I'm still unable to replicate the problem.  Are you on linux srcds? Using Bubbus' acf rockets or acf sweps?

**Comment by monkstick** [comment]
I was on a linux srcds yes (Moved to windows server a few days ago, so I can't test that anymore).  I shall test again.  It only effects bullets using the penetration functions,  explosions are fine.

**Comment by Bubbus** [comment]
This was a problem with my sweps.  For future reference, ensure that any acf bullet's filter contains no NULL entities, or nil indices.  Garry's trace filterer will only read up to the first null/nil and then stop, so everything after that is ignored.  In this case, the debris came after the null...
