### ISSUE TITLE
AP/HEAT Buff

### ISSUE THREAD

**Issue by Amplar** [nrlulz/ACF#165]
They both seem useless.

The idea:

AP: Reduce prop health by 1.5x. I've tested this extensively, it works well. Will invalidate some tanks. Will also make ablative plating less useful, more susceptible to low calibers ripping them off. kind of a good thing.

HEAT: Double the penetration.

**Comment by Redreaper** [comment]
I can see ablatives being more useful because of it.  Will require testing.

I second a buff on HEAT, possibly make it do 100+% more damage + 50% more pen instead?

**Comment by Fervidusletum** [comment]
Added in 2d79aacaa58fadb51d1c5a9e888d1f3c1d581ee4 as a 33% hp nerf and 20% HEAT pen buff.
