### ISSUE TITLE
Bug in savegame

### ISSUE THREAD

**Issue by alexamy** [nrlulz/ACF#169]
I'm having this bug in all my savegames. 
Steam' Garrys Mod is 2015.06.01 version, also I have installed:
Wiremod, Precision Toll, SProps, More Materials!, SmartSnap Fixed, MultiParent, Weight STool, Advanced Duplicator. All these are from Steam Workshop

The problem is: when I start new game (in Sandbox mode on default maps) and place anything from ACF, saves are stop working and I get this message, different is only in 1st point (in script name, depends on part what I've place on map). Its strange what I've played about two hours without problems before. Redownloading ACF didnt help.

Error message in console:
```
[ERROR] addons/acf/lua/entities/acf_gearbox.lua:136: attempt to index local 'Owner' (a nil value)
  1. CreateEntityFromTable - addons/acf/lua/entities/acf_gearbox.lua:136
   2. unknown - lua/includes/modules/duplicator.lua:720
    3. ProtectedCall - [C]:-1
     4. Paste - lua/includes/modules/duplicator.lua:720
      5. unknown - lua/includes/gmsave.lua:58
```

**Comment by Fervidusletum** [comment]
I'm not sure what's happening, will have to look into it.  I would recommend using adv dupe 2 instead of making a savegame, in the mean time. https://github.com/wiremod/advdupe2

**Comment by alexamy** [comment]
Thanks for an advice. I'm currently using Adv Dupe 2 successfully. After next searching on net and asking for advices on servers I came to the conclusion that it is Garry Mod's problem with saves, not the ACF's.

**Comment by Fervidusletum** [comment]
Ok, good to hear.
