### ISSUE TITLE
Engines being very glitchy

### ISSUE THREAD

**Issue by harpwner** [nrlulz/ACF#170]
I make a ton of tanks for ACF in Garry's Mod, but recently (specifically after the new build was released) the engines were not responding to my input... all the time.

only the tanks that run on CVTs work, but not well. I press W to go forward (throttle 100 and all that) and it takes 10 seconds before it goes forward, but never stops when I let go of W, same goes for my tank steering.

I do have plenty of addons installed, but they are all the same addons I used to have when playing with my tanks back when they actually worked. I will try a few more things including reinstalling (for a third time) ACF and uninstalling all other addons except wire and sprops.

I must also mention that no errors are created by trying to drive these things, so there is nothing other than what I've seen and tried here.

EDIT: it is a purely ACF issue, as removing all other addons does not resolve the problem. I also found with the CVT tanks that they only begin moving after I click to reload or shoot a gun.

**Comment by Fervidusletum** [comment]
So far as I know, engine and gearboxes are working as intended.  Make sure you're not overloading the torque rating of gearboxes, that you've got your gearing set up correctly, and that your control wiring is working as it should.

**Comment by harpwner** [comment]
I'm using the same tanks I used in the previous build, unchanged from when they worked... but suddenly after the new build they just cease to work anymore. I've tried replacing everything, checked wiring about 20 times, and looked at all my ratios and engine stuff. There's no way to put it any simpler than my ACF is broken

I'm going to re-install ACF again, is there any possibility of downloading a previous build? I want to see if it truly is the new build or if it is not ACF at all.

**Comment by Fervidusletum** [comment]
It is possible with svn, however it's very unlikely that ACF is the cause of the problem as you're the only person experiencing it.  There would be a lot of complaints on the ACF forum thread if it was broken to the extent you're describing since the last update.  

Try using SVN wire (https://github.com/wiremod/wire) instead of workshop wire, as the gmod update last week broke something and the fix may not have been pushed to workshop wire.

**Comment by harpwner** [comment]
Thank you very much. Wire SVN worked out perfectly. You must have been right since that's around the same time the tanks broke, so using the SVN solved the issue.

**Comment by Fervidusletum** [comment]
Glad that helped. :)
