### ISSUE TITLE
Lua Error when using the ACF Menu tool without anything selected

### ISSUE THREAD

**Issue by brandonsturgeon** [nrlulz/ACF#171]
Doesn't seem like a pressing issue by any means. 

When you left click with the ACF Menu tool selected, it throws an error. (Right clicking does not)

```
22:27:08 Lua Error: [ERROR] addons/acf/lua/weapons/gmod_tool/stools/acfmenu.lua:66: attempt to index a nil value 1. LeftClick - addons/acf/lua/weapons/gmod_tool/stools/acfmenu.lua:66 2. unknown - gamemodes/sandbox/entities/weapons/gmod_tool/shared.lua:254
```

When nothing is selected, `ACF.Weapons[Type][Id]` is nil, so trying to index ["ent"] on it throws errors.

**Comment by Fervidusletum** [comment]
Just to make sure, you've checked to make sure this works, correct?

**Comment by brandonsturgeon** [comment]
I made this patch to my server and no longer saw the error. Granted, it's not a perfect test because I have other addons installed and set up differently. So it'd be best if someone could confirm this works for them too, I imagine.

**Comment by Fervidusletum** [comment]
That's fine, just wanted to check that you tested it. :) Will commit it tomorrow.
