### ISSUE TITLE
HE and APHE dont explodes

### ISSUE THREAD

**Issue by Lightdelablue** [nrlulz/ACF#176]
after i update xcf r534 to acf r552 (i update acf because xcf dont get update https://github.com/Bubbus/XCF).
HE and APHE dont explodes just got AP effect. is a bug or probleme with my server?

the probleme in video: https://www.youtube.com/watch?v=25o9xFjNf40&feature=youtu.be

**Comment by Bubbus** [comment]
Don't use XCF, it's unsupported now.  Use ACF with https://github.com/Bubbus/acf-missiles and https://github.com/Bubbus/acf-sweps instead.

**Comment by Lightdelablue** [comment]
i use acf now but he and aphe not work good :/

**Comment by Bubbus** [comment]
Some maps can affect the ACF effects, try this again on flatgrass and let me know if it's the same.

**Comment by Lightdelablue** [comment]
no explose in flatgrass i think is a probleme with other mod

**Comment by Lightdelablue** [comment]
oh i find the probleme is my fault im stupid ^^""" i subribe that few year ago http://steamcommunity.com/workshop/browse/?appid=4000&searchtext=xcf&childpublishedfileid=0&browsesort=textsearch&section=home is for that i got problme sorry for disturbing ^^"

**Comment by Bubbus** [comment]
Ok, good that you found the problem!

**Comment by Lightdelablue** [comment]
hu no this probleme back again :/
