### ISSUE TITLE
Some realism to engines

### ISSUE THREAD

**Issue by Zengit123** [nrlulz/ACF#177]
In my opinion, it would be fun and realistic to make ACF have:
*Stalling - If the engine experiences hard resistance, it drops RPM and stalls.
*Neccesary clutch - changing gears requires clutch to be disabled from engine, but it can be set with a tick/untick in options, because driving cars is no fun without a neccesary clutch.
*Neccesary fuel - which engine can run without fuel? Tick/untick neccesary fuel in options and have fun.
*Turned on engine with engaged clutch spins wheels even on 0 throttle - like real cars, when your clutch is engaged and first gear is selected, engine is directly connected to wheels and they move.

I have noticed that ACF engines never drop RPM's below the default, I know it might be quite hard to make such a function, but it would open new options in making ACF cars. Every engine has some kind of power, that max power could be used to make one function, where you set how much resistance there has to be to the engine to drop RPM's and stall.
Neccesary clutch with a tick/untick button in options would be super easy to make, and would make drivers have a little more fun driving the cars than clicking W and mouse buttons.
Neccesary fuel would also be super easy to make, just a tick/untick in options and players can do what they want.
Turned on engine with engaged clutch spinning wheels on 0 throttle is also easy to make, because how can a car stand still in first gear and clutch engaged? The default engine RPM's also spin the wheels.

**Comment by Amplar** [comment]
Stalling: Have your idle throttle set to an amount that raises rpm above idle rpm. If less than your upped idle, stall.
Necessary fuel: if tank empty, engine active 0
