### ISSUE TITLE
E:propBreak() Support

### ISSUE THREAD

**Issue by SabertoothPython** [nrlulz/ACF#179]
I think it would be great if ACF supported the propcore E:propBreak command on ammunition crates. It would allow for much more reliable rockets and bombs.

The option for a findInCone/radius to blow up peoples' ammo who come near you is an issue, but no more dangerous than just using propDelete

**Comment by thegrb93** [comment]
if anybody wants to actually do this, you can add this hook to the ammo crate entity: http://wiki.garrysmod.com/page/ENTITY/AcceptInput and check for the "fire" input and explode the crate if it gets that input.

**Comment by Fervidusletum** [comment]
Rockets and bombs are already in the works over at https://github.com/Bubbus/ACF-Missiles .
