### ISSUE TITLE
Cant Install. Please Help

### ISSUE THREAD

**Issue by LoggerTheChicken** [nrlulz/ACF#181]
I am having trouble installing the addon, So I download the addon as a zip and then I extract it to my addons folder then I start up my Gmod then join a singleplayer sandbox game but right before its done loading my game crashes. I do have gbombs 4 installed but I got the ACF and Gbombs compatibility addon so idk if that is the issue. Can someone please help I want to use this addon very badly

**Comment by fakepiratinha** [comment]
did you use linux?

**Comment by redpr1sm** [comment]
I've always had problems installing via zip for whatever reason. Try using SVN or the GitHub app.

**Comment by LoggerTheChicken** [comment]
I solved the issue I had an outdated addon it wasn't ACF that was making me crash it was just coincidence that when I installed ACF the addon become outdated
