### ISSUE TITLE
Check that an engine sound exists before using it.

### ISSUE THREAD

**Issue by thegrb93** [nrlulz/ACF#183]
Massive console spam from "Couldn't play sound "blah", missing from disk or repository"

**Comment by Fervidusletum** [comment]
Engine sound is played with server side function, not currently able to check client and play selectively like weapon sounds. 

Briefly looked into it when doing the same for weapons a while back;  didn't see a method that would work as needed, but I'll have another look.

**Comment by thegrb93** [comment]
I noticed the spam saying a sound was from ACF extras which the server doesn't have installed so I don't think it is just sounds that the player doesn't have.

**Comment by thegrb93** [comment]
Actually I kind of like not having to upload all the sounds to the server. Maybe I can politely ask team garry to move this error output into a higher developer mode.

**Comment by thegrb93** [comment]
https://github.com/Facepunch/garrysmod-requests/issues/553

Setting a console filter will stop sound spam.
