### ISSUE TITLE
[Not working properly] Differentials > Brake

### ISSUE THREAD

**Issue by airidas338** [nrlulz/ACF#184]
Brakes on differentials not working when engine is not active. Please make it work, i want to make handbrake.

**Comment by Fervidusletum** [comment]
Not feasible due to how mobility is designed.

**Comment by airidas338** [comment]
Then redesign it....

**Comment by Bubbus** [comment]
Use a wire clutch or a weld latch to get the braking effect you desire.  If this isn't good enough, ACF is an open project and we welcome appropriate code improvements from everybody, submitted via pull-request.

**Comment by airidas338** [comment]
Clutch and weld latch works like crap... I'll rather use Expression chip with applyAngForce/applyTorque to make brakes...
