### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by PootisMentleGen** [nrlulz/ACF#196]
Even when I have the engine and gearbox facing eachother, I can't get them to link.

**Comment by PootisMentleGen** [comment]
cannot link due to excessive something

**Comment by Bubbus** [comment]
You get that if they're angled too sharply, you can also get it if they're far too close together.  Some of the gearboxes have specific attachment points which are only for wheels or other gearboxes, so try flipping the gearbox by 180 or something like that.
