### ISSUE TITLE
ACF Turbo function

### ISSUE THREAD

**Issue by AnonaMoose21** [nrlulz/ACF#198]
Turbo = Torque*PSI(E2 code using names - PSI = Player defined)"/" if need be for balancing
PSI can not go over real life turbo limit's "Pro turbo's/stage 1's"
if PSI exceed's pro/stage 1 turbo's engine malfunction or break of links(whatever is easier)

**Comment by Fervidusletum** [comment]
Problem with turbos is not function but balance with engine size. Smaller more powerful engines encourage smaller profile tanks.

**Comment by AnonaMoose21** [comment]
this is understandable but you can also blacklist what engine's can and wont work with them.

**Comment by AnonaMoose21** [comment]
Also if you need any help i am more then happy too. i understand the whole gun creation and tuning part of the acf code (i do work for a server on gmod doing acf stuff on request)

**Comment by SeikiMatt** [comment]
Forced induction engines actually consume more fuel at higher RPM and displacement. If you made turbocharged engines have fuel as a requirement (which would have to be done either way for balance) the profile problem could be offset by the need for tanks to store fuel, as they would be completely immobile without it. Of course people would probably try using backup engines to keep mobility but that would add a lot of weight and a enlarge the profile. Guess before it happens, not saying that it will, it would have to be tested for some time.

**Comment by Fervidusletum** [comment]
Unfortunately, I don't think fuel alone is enough of a balance factor. Being able to use a size smaller engine allows plenty of room for fuel without impacting the size of the tank, especially when combined with external drop tanks and fuel saving techniques.

**Comment by VargSkelethor** [comment]
Hey, I think this may be a neat idea for ACF, i would like you and your wonderful team to implement a fire-based weapon to the mod, like incendiary rounds or a flamethrower. The flamerthrower will use fuel and damage props over time, also it will burn large groups of infantry/players. The incendiary rounds will explode and spread a flamable substance which will stick to walls,floors,props,players ect, and will burn for a short period of time. If You find this idea pretty good too then i would love to see it implemented into your mod. Yet again you can alter all of this i've said and put it into a way you will like it. sincerely, VargSkelethor.
