### ISSUE TITLE
Commented weapons by default that rock ?!

### ISSUE THREAD

**Issue by UltimateByte** [nrlulz/ACF#199]
Hey there,

One superadmin from one of my servers just informed me that many weapons in /lua/acf/shared/guns (Howtizer.lua, Cannoon.lua, Mortar.lua, Autoloader.lua) were commented ! He's telling me that they're fully working and that they rock !

So why not uncommenting them into the master repo, so we don't need to do it again after any update ? Why is it commented in the first place ? In developpement ? People complained about it ? Just forgot to uncomment ? :p

**Comment by Fervidusletum** [comment]
They are intentionally commented out as they don't fit how acf is balanced, aside from the mortar which may or may not be added later on.  To be honest the cannon and howitzer should have been removed but I haven't bothered to yet.

**Comment by UltimateByte** [comment]
Thanks for answering. Well, the fact is people using ACF since a while are very happy to see those things. Seems like bigger is better. (i'm not an ACF user myself, but i have feedbacks from people from my community). Maybe a little nerf would solve the problem, but those weapons are desired, i can tell you for sure.

**Comment by UltimateByte** [comment]
Thinking about it again... Would be very nice if you added a svar for additional weapons. :)

(I got an auto updater for ACF now (using https://github.com/UltimateByte/zip-updater and a stop/start command for http://gameservermanagers.com/lgsm/gmodserver/), so it would erase the modifications every time.)

**Comment by UltimateByte** [comment]
Just as a follow up, and so that you know, I now added ACF as an available addon to install directly within LinuxGSM, while preventing `acf-master/lua/acf/shared/guns` from being overwritten upon update as you can see here https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/functions/mods_list.sh#L62
(I had to convert everything to lowercase for it to work because Linux gmod servers don't like caps in addon's title.)

A link to this repo is provided for reference before the install, but if you have a website you would prefer instead, please let me know.

More details about the feature: https://github.com/GameServerManagers/LinuxGSM/wiki/mods-install-update-remove
