### ISSUE TITLE
[request] Speed (4,6,8) transmission additional reverse gear

### ISSUE THREAD

**Issue by SLRR231** [nrlulz/ACF#203]
Speed (4,6,8) transmission additional reverse gear
 I tried hard but the ...

**Comment by shadow7483147** [comment]
Just replace a forward gear with a reversed gear by making it negative (-)
Like so (6 speed):
0.1
0.2
0.3
0.4
-0.1
-0.2
Or use a transfer case

**Comment by SeikiMatt** [comment]
Like shadow7483147 said you can just use transfer cases, they have 2 gears and you can set one to be reverse and one to go forwards (-1, 1). That way you can have 6 normal gears if the transfer case's gear is 1, and 6 reverse reverse gears if your transfer case's gear is -1.
