### ISSUE TITLE
[Request] : Flak

### ISSUE THREAD

**Issue by Avernakis-Fox** [nrlulz/ACF#207]
Obviously not an issue just a request but I was wondering if you could implement Flak cannons or something into acf, it'd add a little more to ground-to-air combat because right now we only have things such as rotary ac's, etc.

I don't know if It's been requested already but, you know just putting it out there. Also loved to hear "boom boom" in the skies in major acf battles from flak. :ok_hand:

**Comment by deathking61** [comment]
i wish we had more sizes for the RAC so we could make a sentry turret and not have this huge gun for something so small

**Comment by AnonaMoose21** [comment]
An idea that can possibly be used is the fuses bubbus used for the missiles to make the gun ammo into flak ammo would need to be on H.E or another ammo type to cause damage the idea just has to run in on do we want e2 fuses or set fuses E2 based ones could/should only work if you have a active target
