### ISSUE TITLE
modding it for my own use 

### ISSUE THREAD

**Issue by deathking61** [nrlulz/ACF#240]
ok, so I'm trying to learn some Lua (doing good so far cause I have been able to mod how far the bullet can go before it arcs to hit the ground ) so what I wanna do now (but what I cannot figure out) is how to change how much recoil (kick) the gun has when it's fired. how would I do this please I would love to know!

**Comment by deathking61** [comment]
ok i managed that no thanks to most of the makers of this addon i love how they really don't actually care.

**Comment by generalwrex** [comment]
Most of us have a lot projects under our belts, I didn't even notice this issue until your second comment notified me. I'm glad you figured it out though!
