### ISSUE TITLE
ACF Bullet Console Spam (Possible) Fix

### ISSUE THREAD

**Issue by vMajx** [nrlulz/ACF#243]
It's my first time using github so i don't know if this is the correct place to type this. 
But i might have a (possible) fix for this issue 

> [ERROR] addons/acf/lua/effects/acf_bulleteffect/init.lua:111: Tried to use invalid object (type CLuaEmitter) (Object was NULL or not of the right type)
Finish - [C]:-1
unknown - addons/acf/lua/effects/acf_bulleteffect/init.lua:111

> [ERROR] addons/acf/lua/effects/acf_bulleteffect/init.lua:136: Tried to use invalid object (type CLuaEmitter) (Object was NULL or not of the right type)
Add - [C]:-1
ApplyMovement - addons/acf/lua/effects/acf_bulleteffect/init.lua:136
ACF_SimBulletFlight - addons/acf/lua/acf/client/cl_acfballistics.lua:25
unknown - addons/acf/lua/effects/acf_bulleteffect/init.lua:39

I've forked ACF and fixed the issues check my profile for the fix or below this post

**Comment by georgeravenholm** [comment]
1sec ill have to teach you how to githubbe

**Comment by deathking61** [comment]
then when can we expect this to be merged with the new acf?

**Comment by Bubbus** [comment]
I don't work on ACF anymore for personal reasons so I haven't been following what's going on, but I was prodded to look at this today and I'm surprised that this is still a problem.

If nobody else is going to do it then I will merge in @vMajx's fix.  Hope this helps.
