### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by isaac81135** [nrlulz/ACF#247]
Everytime I try to load into single player it crashes. I can confirm it is the addon itself because when I remove the ACF folder the map loads without a problem. I installed ACF by making a folder called ACF in my addons folder and then using SVN tortoise to do a checkout with this link: https://github.com/nrlulz/ACF/trunk . After installing it gave me like something that said MLX error and it also said operation failed, I checked the files and everything was there but just to be sure I re downloaded ACF using the same method and the same error came up so I figured it was something that was supposed to happen. I tried looking for crash reports in the game's folder but it seems they don't print everytime it crashes via ACF.

**Comment by deathking61** [comment]
ok first off don't use SVN use the one here or i can send you a version i did its the one before this one as this one has nothing but issues..............oh and i enabled weld-parenting on all things so there is that and before you say "it's not realistic" let me remind you that only doing a weld isn't efficient at all and that creates lagg whereas the way I'm doing it reduces this effect down to next to none so yea.

**Comment by isaac81135** [comment]
The problem a actually was I had too many addons enabled. Thanks for trying
to help though.
