### ISSUE TITLE
ACF Update 604 not available

### ISSUE THREAD

**Issue by Darklight1754** [nrlulz/ACF#260]
I have been stuck on ACF Version 599, I have tried downloading the ZIP File and also the SVN Checkout with Tortoise SVN and I keep getting the same results. Is this page not updated with the current version?

**Comment by Bubbus** [comment]
It is - please see here and make sure your installation matches these details:

https://github.com/nrlulz/ACF/blob/master/readme.txt

If that doesn't help, I'm stumped.  The ZIP file should definitely have the latest version so it really does seem like an install-specific issue.

**Comment by Darklight1754** [comment]
I redownloaded the ZIP, extracted it to my addons and still have Version 599. I even have pictures for proof.  I deleted the last ACF Master file I had prior to redownloading the "newest" version on the github.
http://steamcommunity.com/sharedfiles/filedetails/?id=1301751105
Here is the in-game photo that displays the version I have.
