### ISSUE TITLE
Ricochet mechanics

### ISSUE THREAD

**Issue by noth1ng1996** [nrlulz/ACF#266]
According to next code:
```
-- sv_acfdamage.lua, ACF_RoundImpact() @ line 262 and ACF_PenetrateGround() @ line 309
local MinAngle = math.min(Bullet["Ricochet"] - Speed/39.37/18,89)
if Angle > math.random(MinAngle,90) and Angle < 89.9 then
         -- Ricochet
end
```
Ricochet probability function is shown on next graph:

![graph1](https://user-images.githubusercontent.com/10603966/38423542-e68e5614-39b6-11e8-9187-44b59589e25d.png)

As it can be seen, impact angle with 0% ricochet probability is MinAng.

_The problem is that the value of MinAng is not restricted in any way, so it is possible for it to become less then 0, as speed of projectile increases, giving probability of ricochet at 0 degrees larger than 0._

In other words (in extreme case) it is possible for 203mm projectile to ricochet from 0.1mm armor plate at 0 degrees, if it is fast enough (**What!?**). **This is obviously broken mechanics!** This implementaion does not correlate with real-world physics or similar mechanics seen in other games, which leads to unpredictability at what angle projectile will ricochet or not. It also lowers predicability of tank designs relying on sloped armor and hugely increases effectiveness of armor consisting of large number of thin layers.

Solution to this problem would be implementation of constant angles with 0% and 100% ricochet probabilities for each type of projectile (like in War Thunder, but a bit simpler; values also could be taken from there) and armor breach mechanics (also like in War Thunder: if round's caliber is larger than armor * 7 - there is no ricochet). It also would be good idea to display those values in ammo creation menu.

**Comment by Bubbus** [comment]
Thanks for the writeup.  It's been known for a while that ricochets in ACF are not properly implemented, but developer interest seems to have died out on the issue.

I'm accepting pull-requests from the community for a wide variety of additions or modifications, so if you or anyone else can provide a well-written solution for this then I'd be glad to make it a part of ACF.

**Comment by thegrb93** [comment]
I think probing a log-normal distribution with the mode at 90 degrees and sigma dependent on velocity would work nicely
