### ISSUE TITLE
Rockets curl wildly at certain angles

### ISSUE THREAD

**Issue by TheMrFailz** [nrlulz/ACF#271]
https://youtu.be/IXeLpZgn130

In the vid the RS-82 rockets coming off of the small 1x rocket mount just curl wildly. However (not seen in video), at most other angles they fly perfectly fine.

**Comment by TheMrFailz** [comment]
Sending this and I don't know if it will go through because it's through
email but oh crap sorry forgot that this was the regular ACF one and not
the missiles

**Comment by deathking61** [comment]
actually, there isn't anything wrong with them its the part of the code that determines accuracy so if you lower that number then they won't do that. I know cause I fixed it on my end................
