### ISSUE TITLE
Mobility is shot for me

### ISSUE THREAD

**Issue by TheLightBringer1991** [nrlulz/ACF#275]
All my acf tanks are dead with the new acf version. There is no way to make them turn at all and there is no fix, I was helped by Fervidusletum too, but not even him could fix my problem.
He tried reconstraining, new gearbox, engine and e2s.
Feels like my tanks don't have enough torque to turn from idle, they can just barely turn while already moving.

**Comment by Bubbus** [comment]
Does your tank use turbines?  I've just tested with a turbine tank and a piston tank and the turbine one doesn't move, while the piston engine works just as before.

Maybe @thegrb93 can help?

**Comment by thegrb93** [comment]
Any chance I can get a copy of the dupe file? I haven't had any users on my server complaining about it thus far, but I can check.

**Comment by TheLightBringer1991** [comment]
https://garrysmods.org/download/59872/isu-152-oversized-130

This is an older dupe, but uses th

**Comment by thegrb93** [comment]
There's two problems. It's hitting the torque limit, and while turning its torque is 0 for several frames (due to clutch or gearing? idk). The solution to the first problem is easy, just raise the torque limit. Idk at which threshold it starts crashing servers but I set it to x5 and seemed fine. The second problem Idk whats causing it or what the fix is, but the torque looks like this while turning.

```
107763.039063 -31610.310547 4176.890625
0.000000 -0.000000 0.000000
0.000000 -0.000000 0.000000
0.000000 -0.000000 0.000000
122461.953125 -31728.701172 4776.541016
0.000000 -0.000000 0.000000
0.000000 -0.000000 0.000000
0.000000 -0.000000 0.000000
99553.781250 -22324.871094 3884.562256
0.000000 -0.000000 0.000000
0.000000 -0.000000 0.000000
0.000000 -0.000000 0.000000
124314.093750 -23432.505859 4835.100098
0.000000 -0.000000 0.000000
0.000000 -0.000000 0.000000
0.000000 -0.000000 0.000000
119268.398438 -18190.779297 4614.806641
0.000000 -0.000000 0.000000
0.000000 -0.000000 0.000000
0.000000 -0.000000 0.000000
125669.742188 -14491.272461 4855.520996
0.000000 -0.000000 0.000000
0.000000 -0.000000 0.000000
0.000000 -0.000000 0.000000
126124.679688 -9767.383789 4859.990234
0.000000 -0.000000 0.000000
0.000000 -0.000000 0.000000
0.000000 -0.000000 0.000000
126408.171875 -4871.986328 4867.769531
0.000000 -0.000000 0.000000
0.000000 -0.000000 0.000000
0.000000 -0.000000 0.000000
126503.226563 153.752274 4833.834473
0.000000 0.000000 0.000000
0.000000 0.000000 0.000000
0.000000 0.000000 0.000000
126391.867188 5311.730469 4830.872070
0.000000 0.000000 0.000000
0.000000 0.000000 0.000000
0.000000 0.000000 0.000000
126061.390625 10600.567383 4755.062988
0.000000 0.000000 0.000000
0.000000 0.000000 0.000000
0.000000 0.000000 0.000000
125493.000000 15982.665039 4745.241699
0.000000 0.000000 0.000000
0.000000 0.000000 0.000000
0.000000 0.000000 0.000000
124678.671875 21437.140625 4704.645996
```

**Comment by thegrb93** [comment]
I should've printed CurTime to see which frame the 0 torque are on. I'll try that when I get back.

**Comment by thegrb93** [comment]
I've found the 0 torque comes from the drivetrain. Idk how the whole system works, but probably normal.
