### ISSUE TITLE
Can't Create Entity

### ISSUE THREAD

**Issue by Grave-Accent** [nrlulz/ACF#277]
Whenever I try to create anything with ACF all I get is an error saying "can't create entity" and the console says something about the entity not having a "type" key.

**Comment by thegrb93** [comment]
You have to put the whole console message

**Comment by Grave-Accent** [comment]
ERROR: Trying to derive entity acf_gun from non existant entity base_wire_entity!
Error: Tried to make a SENT (acf_gun) but it didn't have a 'Type' key!
Attempted to create unknown entity type acf_gun!

**Comment by thegrb93** [comment]
You need wire https://github.com/wiremod/wire
