### ISSUE TITLE
[ERROR] addons/acf/lua/entities/acf_gearbox.lua:914: attempt to call method 'ApplyTorqueCenter' (a nil value)

### ISSUE THREAD

**Issue by Jason1232Q** [nrlulz/ACF#279]
Spams following error when something is spawned.

L 07/04/2018 - 19:37:14: Lua Error:
[ERROR] addons/acf/lua/entities/acf_gearbox.lua:911: attempt to call method 'ApplyTorqueCenter' (a nil value)
1. ActWheel - addons/acf/lua/entities/acf_gearbox.lua:911
2. Act - addons/acf/lua/entities/acf_gearbox.lua:878
3. CalcRPM - addons/acf/lua/entities/acf_engine.lua:598
4. unknown - addons/acf/lua/entities/acf_engine.lua:426

**Comment by Jason1232Q** [comment]
Well, the server is up to date. Backdating the version of ACF worked.

**Comment by thegrb93** [comment]
What do you get with `lua_run print(VERSION)`? should be 180528

**Comment by Jason1232Q** [comment]
Its 180223 however steamcmd validates it every launch

**Comment by thegrb93** [comment]
I think because the devs marked the update as optional. Weird I know

**Comment by Jason1232Q** [comment]
Sooo, how would i go about fixing this?

**Comment by thegrb93** [comment]
update it
