### ISSUE TITLE
Rail guns??? And mabey makeing composite Armour actually useable

### ISSUE THREAD

**Issue by Ratakis** [nrlulz/ACF#293]
Could we add railguns and actually make composite Armour useable instead of using fucking cheese wedges as the front plate.

**Comment by Drizzii** [comment]
ACF is a mod based in the 60's, usable combat railguns didnt exist back then.
Composite Armor is simulated by Ductility/Hardness, so its already useable.
Also HEAT eats cheese wedges unless they have composite soooo

**Comment by Ratakis** [comment]
Well we can update the years reeeeeeeeeeeeeeeee
