### ISSUE TITLE
Engine not running properly (won't rev up nor put power down)

### ISSUE THREAD

**Issue by SumNutz** [nrlulz/ACF#295]
when turning the engine on it starts with the rpm slowly lowering down to idle, when activating the throttle, it won't rev up. i've debbuged it, torque output is too low (close to none, about 2) on almost all engines, if not all of them. any ideas?

**Comment by Amplar** [comment]
Have you change the weight of the motor, or parented it?

**Comment by SumNutz** [comment]
... i feel like shit. thanks for the help and patience for my stupidity, it was because of the input.

**Comment by Amplar** [comment]
Not dumb at all, it's not really something that said anywhere. I figured that was the issue when you said it slowly revved down. I often use a bit of residual throttle to simulate engine braking.
