### ISSUE TITLE
Help! Gearbox is creating Script Errors

### ISSUE THREAD

**Issue by sukablyatrushB** [nrlulz/ACF#298]
I followed tutorials on how to make a basic car in ACF and I have done everything but everytime I enter my seat I get Script Errors

**Comment by Jophes** [comment]
We'll need to know what the console errors are, otherwise we can't do anything.

**Comment by sukablyatrushB** [comment]
this is one

[ERROR] addons/acf-master/lua/entities/acf_gearbox.lua:911: attempt to call method 'ApplyTorqueCenter' (a nil value)
  1. ActWheel - addons/acf-master/lua/entities/acf_gearbox.lua:911
   2. Act - addons/acf-master/lua/entities/acf_gearbox.lua:878
    3. CalcRPM - addons/acf-master/lua/entities/acf_engine.lua:598
     4. unknown - addons/acf-master/lua/entities/acf_engine.lua:426

**Comment by thegrb93** [comment]
Your server/game needs to be updated

**Comment by sukablyatrushB** [comment]
I have GMod 16 is that enough?

**Comment by thegrb93** [comment]
Duplicate of https://github.com/nrlulz/ACF/issues/279

**Comment by sukablyatrushB** [comment]
I ran the command and I got 160424
