### ISSUE TITLE
Speed limiting issue

### ISSUE THREAD

**Issue by TacoSalad7** [nrlulz/ACF#300]
Even after trying the demo_avellimit 60000 fix, i still cant go past 27 mph no matter what. I saw something about a script but it 404'd. Any soloutions for this problem that has been plauging me for so damn long?

**Comment by TacoSalad7** [comment]
even after putting this: lua_run local tbl = physenv.GetPerformanceSettings() tbl.MaxAngularVelocity = 30000 physenv.SetPerformanceSettings(tbl)

lua_run local tbl = physenv.GetPerformanceSettings() tbl.MaxVelocity = 20000 physenv.SetPerformanceSettings(tbl) in my server.cfg file it still is limited to 27 mph.

**Comment by thegrb93** [comment]
Torque is limited to stop server crashes. Any higher than these would probably explode the gearbox anyway

https://github.com/nrlulz/ACF/blob/a29342f6ad393fe72aeb7eec8ffd2f0ccb8eb661/lua/entities/acf_gearbox.lua#L892
https://github.com/nrlulz/ACF/blob/a29342f6ad393fe72aeb7eec8ffd2f0ccb8eb661/lua/entities/acf_gearbox.lua#L910

**Comment by TacoSalad7** [comment]
What does the issue have to do with torque?

**Comment by thegrb93** [comment]
You need enough torque to overcome resistance to get more speed

**Comment by thegrb93** [comment]
If it's the engine angular speed limit you're hitting then this isn't the place to be posting the issue.

**Comment by TacoSalad7** [comment]
Where should I post this issue, and are there any fixes you may know of?
