### ISSUE TITLE
Entire vehicle being deleted by "Crazy origin, angles, velocity, angular velocity" error

### ISSUE THREAD

**Issue by jiant0** [nrlulz/ACF#305]
Having a peculiar issue which originally kept resulting in my entire vehicle being deleted. The error looks like this (the values are always the same):
```
Crazy origin, angles, velocity, angular velocity on entity [160][gmod_wire_button]
	Origin:           [nan, nan, -nan(ind)]
	Angles:           [nan, nan, 180.000000]
	Velocity:         [nan, nan, -nan(ind)]
	Angular Velocity: [nan, nan, -nan(ind)]
```
I set `sv_crazyphysics_remove` to 0 to prevent it from deleting itself, and instead it seems to teleport and freeze everything at some position in the map, which looks like this:
![error result](https://i.imgur.com/NA9yI7k.jpg)

Here is what my chassis looks like normally:
![normal form](https://i.imgur.com/Vew3UFl.jpg)

I can't reliably reproduce the issue, but it seems to almost always happen when releasing the throttle.

**Comment by Fervidusletum** [comment]
This looks like an issue with your contraption, not with ACF.  It looks like you have multiple physical bases between the wheels, it's much more common (and reliable) to have the floor of your tank armor be the baseplate, and everything is constrained to that,
