### ISSUE TITLE
[Not an issue] Make gearboxes accept inputs from props too.

### ISSUE THREAD

**Issue by TheLightBringer1991** [nrlulz/ACF#306]
Right now gearboxes can only take inputs from acf engines and output to other gearboxes or props. Would be nice to have the ability to input power to gearboxes from props too, so the normal acf gearboxes can be used with prop engines or similar. Maybe have a special gearbox for that, instead of needlessy changing them all to do that. Is it possible?

**Comment by Fervidusletum** [comment]
Gearboxes for prop engines can easily be replicated in e2 (use gear ratios to calculate torque and rpm to wheels, apply a proportional counterforce to the driveshaft). No need for acf to handle it, and avoids having to deal with balance issues that would come with prop-to-acf gearboxes.
