### ISSUE TITLE
Engine RPM Bug

### ISSUE THREAD

**Issue by basiotte** [nrlulz/ACF#316]
Engine sound and RPM won't work properly when has 2 differentials in sequence after a gearbox

**Comment by Amplar** [comment]
Make sure the differentials and engine are their default weight, and if it is a geared transmission (4,6,8spd) it isn't parented.

**Comment by basiotte** [comment]
i have the diffs in the right weight, when i have engine > gearbox > diff > another diff, when i release throttle, the engine rpm do not work with the wheels rotation, it just go idle like i'm pressing clutch

**Comment by basiotte** [comment]
and, engine, transmission, diffs and fuel, works parented, but you have to parent it with weld

**Comment by Amplar** [comment]
Only engine amd gearbox need a weld. To make them work while parented and welded, they must be parented to what they are welded to.

**Comment by basiotte** [comment]
i know, but the bug is when i release throttle, it acts like i'm pressing clutch, i can give a copy of 2 cars of mine to compare the situation

**Comment by Amplar** [comment]
That's how acf engines behave, there is no reactionary torque so they clutch to not stall. You gotta code it to behave differently

**Comment by basiotte** [comment]
but in this car that i have sequential diffs, it happens, but my other cars do not have this

**Comment by basiotte** [comment]
if you want, i can show it to you, or just give you my 2 new cars, 1 that have this issue, and other without it

**Comment by basiotte** [comment]
its the car that have this issue 
[evo4_18.txt](https://github.com/nrlulz/ACF/files/3000321/evo4_18.txt)

**Comment by basiotte** [comment]
and its the last one that i made without this bug 
[s14d_68.txt](https://github.com/nrlulz/ACF/files/3000323/s14d_68.txt)

**Comment by basiotte** [comment]
to drive then W is half throttle, W+Shift is full throttle, hold F to show the crosshair and mouse 1 to click on the start button, V is the clutch, and you have to do clutch to change gears, M1 GearUp M2 GearDn, R is reverse toggle also needs clutch
