### ISSUE TITLE
Propdraw tanks that take no damage 

### ISSUE THREAD

**Issue by Ratakis** [nrlulz/ACF#318]
Please outlaw propdraw for tank use "including armor" To make things more balanced and fair thanks.

**Comment by thegrb93** [comment]
Shouldn't that be the server's responsibility?

**Comment by Ratakis** [comment]
not many people know about it

**Comment by Ratakis** [comment]
but it is still very abusive

**Comment by CheezusChrust** [comment]
The only thing you can do is make its existence known and get people to write rules about it for their servers, there isn't anything the ACF devs can do about it to my knowledge.

**Comment by thegrb93** [comment]
will do about it*

**Comment by thegrb93** [comment]
They can do something about it. It's just no one develops for it anymore.
