### ISSUE TITLE
E2 crash game with gearbox

### ISSUE THREAD

**Issue by ShadowMiner** [nrlulz/ACF#321]
Game crash on changing gear to neutral or reverse with this chip

https://pastebin.com/2t6a9Fa5

For reverse gear using transfer gearboxes, not the main gearbox.

**Comment by ShadowMiner** [comment]
I made some researches, and it is not transfer gearboxes issue, it is issue with changing gear to neutral or switching gear to lower with this e2.

**Comment by thegrb93** [comment]
Need a dupe of the setup. There's not enough information here to reproduce it.

**Comment by ShadowMiner** [comment]
Just drive some time and try to switch to neutral gear.
[BugCar.txt](https://github.com/nrlulz/ACF/files/3294677/2.txt)

**Comment by thegrb93** [comment]
Doesn't crash

**Comment by thegrb93** [comment]
Nvm, it's a crazy physics thing.

**Comment by thegrb93** [comment]
There's some very specific and hard to reproduce case where its forces becomes NAN which triggers the crazy physics removal. Shouldn't crash though unless you have that turned off.

**Comment by thegrb93** [comment]
I see lots of potential in acf_gearbox.lua for 0*math.huge or 0/0 or math.huge/math.huge. All of which will produce a NAN. I suggest checking them all and making sure safeguards are in place.

**Comment by thegrb93** [comment]
Probably this one https://github.com/nrlulz/ACF/blob/master/lua/entities/acf_gearbox.lua#L862

Not checking if gearratio is 0.

**Comment by ShadowMiner** [comment]
This happens only with high power from engines as i understand.

**Comment by thegrb93** [comment]
Yep, I was right. Torque is infinity in that Act function when it happens.

**Comment by thegrb93** [comment]
Try changing that line to
`if Torque ~= 0 and self.GearRatio ~= 0 then`

and see if that fixes it @ShadowMiner

**Comment by thegrb93** [comment]
https://github.com/nrlulz/ACF/blob/master/lua/entities/acf_gearbox.lua#L862

**Comment by ShadowMiner** [comment]
Seems it removed crash.
