### ISSUE TITLE
Cannot link due to excessive driveshaft angle!

### ISSUE THREAD

**Issue by dumbuz** [nrlulz/ACF#323]
I have tried so hard to link this stupid clutch to this wheel, but no matter how hard I try, it still does not work. Please help me 
![image](https://user-images.githubusercontent.com/44739965/59800514-0d7b7f80-92a4-11e9-8ee1-6508136a2c20.png)

**Comment by thegrb93** [comment]
Which clutch specifically is it?

**Comment by TheGameTrain** [comment]
@thegrb93 Clutch, Straight, Large
And the engine is a 7.8L V6 Diesel
