### ISSUE TITLE
I think ACF cannons and ammo are too heavy for reality.

### ISSUE THREAD

**Issue by Morokei035** [nrlulz/ACF#326]
It doesn't make sense that 120mm cannon is 5.2t.
and ammocreats are too heavy. 
of course, artillery shell is heavy as ACF. but it's too heavy for Tank gun shell.
why don't you reduce the weight of cannons?
And, while maintaining the weight of the howitzer ammo, it would be better to reduce the weight of the tankgun ammo.
thank you.

#Dokkaebi

**Comment by Amplar** [comment]
It's to simulate the weight of the ammo stowage components, loaders, gun mounts and turret systems, etc.
