### ISSUE TITLE
engine performance bug

### ISSUE THREAD

**Issue by mogu852** [nrlulz/ACF#335]
if high physical weight entity was ball-socketed(ball-socket advance) to the center entity(it's welded to the engine), then the engine's performance is an increase. Developers, Please fix this bug.

**Comment by LofisisHomeless** [comment]
It's how the engine compensates Parent/Physical-Weight.
It's hard to balance this.
I wouldn't consider this a bug.
It's more like a feature based on  Parent/Physical-Weight. of every engine.

It's only unfair when it gets to like. Racecars lol.
if tanks abuse it they will exceed their maximum weight. Ending up as an illegal tank weight wise.

**Comment by thegrb93** [comment]
I don't recall engines or gearbox's torque depending on weight.

**Comment by mogu852** [comment]
if parented prop was ball-socketed with base prop, it works like physics prop. but it dosn't have physical mass effect. like weld-parent effect. so it can abuse about tank or car's increase engine performance.

example, ball-socket tank's physics prop (engine, gun, turret base prop, gearbox ...) to base prop.

**Comment by mogu852** [comment]
if parented prop was ball-socketed, it works like weld-parent prop.
ex) tank's physics prop, parented heavy armor prop.
