### ISSUE TITLE
" 'for' limit must be a number" gearbox error spamming console occasionally

### ISSUE THREAD

**Issue by CheezusChrust** [nrlulz/ACF#347]
Unsure what causes this, can't find any specific way to reproduce. I noticed it happens randomly with general use of ACF gearboxes. Doesn't cause any issues in game as far as I know, just annoying to see.

![YwzpewL](https://user-images.githubusercontent.com/21130637/68536876-eba09900-0327-11ea-91f8-d839d8740437.png)

**Comment by thegrb93** [comment]
If you paste every lua error spam acf has then this issue tracker will be flooded
