### ISSUE TITLE
No sound or effects

### ISSUE THREAD

**Issue by I-Dont-Even-Know-Anymore** [nrlulz/ACF#404]
So, when I shoot, no sound is played and there's no muzzle break. Also, when I blow up an ammo box, there are no explosions. Everything works like normal, but there are no effects or sounds. The engines work perfectly, even the sounds, that engines make work. (installed with SVN)

Please help, I have this issue for more than 7 months now.

**Comment by TheLightBringer1991** [comment]
Does it happen all the time? Because sometimes ACF shits itself for a moment and no sound or effects are played, but next shot works fine.

**Comment by I-Dont-Even-Know-Anymore** [comment]
> Does it happen all the time? Because sometimes ACF shits itself for a moment and no sound or effects are played, but next shot works fine.

Yes, it happens all the time.

**Comment by I-Dont-Even-Know-Anymore** [comment]
So, after the last gmod update, the game didn't want to load, so I reinstalled it, the issue disappeared.
