### ISSUE TITLE
Workshop & ACF

### ISSUE THREAD

**Issue by Anticept** [nrlulz/ACF#63]
There was a discussion going in the Wiremod Workshop about ACF (http://steamcommunity.com/workshop/filedetails/discussion/160250458/864974880624851382/#p1), and there's something I wanted to straighten out.

Bubbus was talking about separating the extras from ACF into several packs so people don't have to re-download a lot of things on changes. Workshop has long since changed; unless everything is wrapped up in one big superfile (even then I think it hashes and distributes blocks), it will only push deltas.

Also, I believe we use Jenkins (http://jenkins-ci.org/) to push workshop updates. We have it set up to monitor a workshop branch on github, and when we push to it, jenkins will then push to the workshop.

Figured that info would be useful to you guys.

**Comment by devSera** [comment]
May be worth reconsidering now that the maximum workshop limit has been raised.

![image](https://user-images.githubusercontent.com/15877760/75461050-35050a80-5950-11ea-8409-6039244a52b4.png)
